[versions]
agp = "9.3.2"
okhttp = "5.5.0"
activity = "1.13.0"
jbbp = "3.0.3"
preference = "1.2.1"
appcompat = "1.8.0"
material = "1.14.0"

[libraries]
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
jbbp = { module = "com.igormaznitsa:jbbp", version.ref = "jbbp" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }